/**
 * Interactive setup wizard for bk-quiz
 * Run: npm run setup
 */

import { existsSync, writeFileSync } from 'fs';
import * as readline from 'node:readline';

const ENV_PATH = './.env';

function rlQuestion(prompt: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function print(title: string, message: string): void {
  console.log(`\n${title} ${message}`);
}

async function main(): Promise<void> {
  console.log('╔══════════════════════════════════════════════╗');
  console.log('║     🎓 bk-quiz Setup Wizard                  ║');
  console.log('║     One-time configuration                   ║');
  console.log('╚══════════════════════════════════════════════╝');

  // Check if .env already exists
  if (existsSync(ENV_PATH)) {
    const overwrite = await rlQuestion('\n.env already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled. Your existing .env is untouched.');
      process.exit(0);
    }
  }

  // Provider selection
  console.log('\n📡 Step 1: Choose your AI provider');
  console.log('  1) Groq — FREE, fast, recommended ⭐');
  console.log('  2) OpenAI — paid, best quality');
  console.log('  3) Ollama — free, offline (requires local server)');

  const providerChoice = await rlQuestion('\nEnter 1, 2, or 3 (default: 1): ');
  const providerMap: Record<string, string> = {
    '1': 'groq',
    '2': 'openai',
    '3': 'ollama',
    '': 'groq',
  };
  const provider = providerMap[providerChoice] || 'groq';

  let envContent = `# bk-quiz configuration
# Generated by: npm run setup

`;

  if (provider === 'groq') {
    console.log('\n📝 Step 2: Get your FREE Groq API key');
    console.log('   → https://console.groq.com/keys');
    console.log('   → Sign up (no credit card required)');
    console.log('   → Create API key (starts with gsk_)');
    const apiKey = await rlQuestion('\nPaste your Groq API key: ');
    envContent += `LLM_PROVIDER=groq
GROQ_API_KEY=${apiKey}\n`;
  } else if (provider === 'openai') {
    console.log('\n📝 Step 2: Get your OpenAI API key');
    console.log('   → https://platform.openai.com/api-keys');
    const apiKey = await rlQuestion('\nPaste your OpenAI API key: ');
    envContent += `LLM_PROVIDER=openai
OPENAI_API_KEY=${apiKey}\n`;
  } else {
    console.log('\n📝 Ollama selected. Make sure you run: ollama serve');
    const endpoint = await rlQuestion('Ollama endpoint (default: http://localhost:11434): ');
    const model = await rlQuestion('Model name (default: mistral): ');
    envContent += `LLM_PROVIDER=ollama
OLLAMA_ENDPOINT=${endpoint || 'http://localhost:11434'}
OLLAMA_MODEL=${model || 'mistral'}\n`;
  }

  // Optional: question limit
  console.log('\n⚙️  Optional: Maximum questions per quiz (default: 500)');
  const limit = await rlQuestion('Enter limit or press Enter for default: ');
  if (limit && !isNaN(parseInt(limit, 10))) {
    envContent += `MAX_QUESTIONS=${parseInt(limit, 10)}\n`;
  }

  writeFileSync(ENV_PATH, envContent, 'utf-8');

  console.log('\n✅ .env file created successfully!');
  console.log('   Run `npm run start` to begin.');
}

main().catch((err) => {
  console.error('Setup failed:', err.message);
  process.exit(1);
});
